# Generated by Django 5.2.10 on 2026-03-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('team', models.CharField(blank=True, max_length=100, null=True)),
                ('position', models.CharField(blank=True, max_length=50, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='players/')),
                ('photo_filename', models.CharField(default='default_player.jpg', help_text='Имя файла фото в static/images/players/', max_length=100)),
                ('hand', models.CharField(blank=True, max_length=20, null=True)),
                ('specialty', models.CharField(blank=True, max_length=100, null=True)),
                ('generation', models.CharField(blank=True, max_length=50, null=True)),
                ('number', models.IntegerField(blank=True, null=True)),
                ('other_info', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('rost', 'Стартовый состав'), ('bench', 'Запасные'), ('senior', 'Старшие игроки'), ('hall', 'Hall of Fame')], default='rost', max_length=10)),
            ],
        ),
    ]
