# Generated by Django 5.2.10 on 2026-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_player_options_remove_player_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='photo_filename',
            field=models.CharField(default='default_player.jpg', help_text='Имя файла фото в static/images/players/', max_length=100),
        ),
    ]
