# Generated by Django 5.2.10 on 2026-03-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_player_number_player_photo_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='achievements',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('rost', 'Стартовый состав'), ('hall', 'Hall of Fame')], default='rost', max_length=10),
        ),
    ]
