# Generated by Django 5.2.10 on 2026-03-09 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_player_achievements_player_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='player',
            options={'ordering': ['number', 'name'], 'verbose_name': 'Игрок', 'verbose_name_plural': 'Игроки'},
        ),
        migrations.AddField(
            model_name='player',
            name='total_matches',
            field=models.IntegerField(default=0, verbose_name='Всего матчей'),
        ),
        migrations.AddField(
            model_name='player',
            name='total_points',
            field=models.IntegerField(default=0, verbose_name='Всего очков'),
        ),
        migrations.AlterField(
            model_name='player',
            name='achievements',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Достижения'),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.IntegerField(blank=True, null=True, verbose_name='Возраст'),
        ),
        migrations.AlterField(
            model_name='player',
            name='category',
            field=models.CharField(choices=[('rost', 'Стартовый состав'), ('bench', 'Запасные'), ('senior', 'Старшие игроки'), ('hall', 'Hall of Fame')], default='rost', max_length=10, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='player',
            name='generation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Поколение'),
        ),
        migrations.AlterField(
            model_name='player',
            name='hand',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Рука'),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рост (см)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, null=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='player',
            name='other_info',
            field=models.TextField(blank=True, null=True, verbose_name='Доп. информация'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='players/', verbose_name='Фото (загрузка)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='photo_filename',
            field=models.CharField(default='default_player.jpg', help_text='Имя файла в static/images/players/', max_length=100, verbose_name='Фото (файл)'),
        ),
        migrations.AlterField(
            model_name='player',
            name='position',
            field=models.CharField(blank=True, choices=[('PG', 'Разыгрывающий'), ('SG', 'Атакующий защитник'), ('SF', 'Легкий форвард'), ('PF', 'Тяжелый форвард'), ('C', 'Центровой'), ('UNK', 'Неизвестно')], default='UNK', max_length=50, null=True, verbose_name='Позиция'),
        ),
        migrations.AlterField(
            model_name='player',
            name='slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='player',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Специализация'),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Команда'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.IntegerField(blank=True, null=True, verbose_name='Вес (кг)'),
        ),
        migrations.CreateModel(
            name='Tactic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название тактики')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='URL')),
                ('tactic_type', models.CharField(choices=[('offense', 'Атака'), ('defense', 'Защита')], default='offense', max_length=10, verbose_name='Тип')),
                ('zone', models.CharField(blank=True, choices=[('3-2', 'Против зоны 3-2'), ('2-3', 'Против зоны 2-3'), ('man', 'Person-to-Person'), ('zone', 'Зонная защита'), ('fastbreak', 'Быстрый отрыв')], max_length=10, verbose_name='Против зоны')),
                ('description', models.TextField(verbose_name='Описание')),
                ('difficulty', models.CharField(choices=[('E', 'Легко'), ('M', 'Средне'), ('H', 'Сложно')], default='M', max_length=1, verbose_name='Сложность')),
                ('video_url', models.URLField(blank=True, help_text='Например: https://www.youtube.com/embed/...', verbose_name='Ссылка на видео (YouTube)')),
                ('video', models.FileField(blank=True, null=True, upload_to='tactics/videos/', verbose_name='Видео файл')),
                ('diagram', models.ImageField(blank=True, null=True, upload_to='tactics/diagrams/', verbose_name='Схема (картинка)')),
                ('player_positions', models.JSONField(blank=True, default=list, help_text='Формат: [[x1,y1], [x2,y2], ...] для 5 игроков', verbose_name='Позиции игроков')),
                ('movements', models.JSONField(blank=True, default=list, help_text="Формат: [{'from': [x,y], 'to': [x,y], 'type': 'pass'}]", verbose_name='Движения')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('featured_players', models.ManyToManyField(blank=True, related_name='tactics', to='main.player', verbose_name='Игроки в тактике')),
            ],
            options={
                'verbose_name': 'Тактика',
                'verbose_name_plural': 'Тактики',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_x', models.IntegerField(default=0, verbose_name='Начало X')),
                ('start_y', models.IntegerField(default=0, verbose_name='Начало Y')),
                ('end_x', models.IntegerField(default=0, verbose_name='Конец X')),
                ('end_y', models.IntegerField(default=0, verbose_name='Конец Y')),
                ('movement_type', models.CharField(choices=[('pass', 'Пас'), ('move', 'Перемещение'), ('shot', 'Бросок'), ('screen', 'Заслон')], default='move', max_length=10, verbose_name='Тип')),
                ('order', models.IntegerField(default=0, verbose_name='Порядок')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.player')),
                ('tactic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements_list', to='main.tactic')),
            ],
            options={
                'verbose_name': 'Движение',
                'verbose_name_plural': 'Движения',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(max_length=100, verbose_name='Соперник')),
                ('date', models.DateTimeField(verbose_name='Дата и время')),
                ('is_home', models.BooleanField(default=True, verbose_name='Дома')),
                ('our_score', models.IntegerField(default=0, verbose_name='Наш счет')),
                ('opponent_score', models.IntegerField(default=0, verbose_name='Счет соперника')),
                ('is_finished', models.BooleanField(default=False, verbose_name='Завершен')),
                ('description', models.TextField(blank=True, verbose_name='Описание матча')),
                ('tactics_used', models.ManyToManyField(blank=True, related_name='matches', to='main.tactic')),
            ],
            options={
                'verbose_name': 'Матч',
                'verbose_name_plural': 'Матчи',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='MatchPlayerStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0, verbose_name='Очки')),
                ('rebounds', models.IntegerField(default=0, verbose_name='Подборы')),
                ('assists', models.IntegerField(default=0, verbose_name='Передачи')),
                ('steals', models.IntegerField(default=0, verbose_name='Перехваты')),
                ('blocks', models.IntegerField(default=0, verbose_name='Блок-шоты')),
                ('turnovers', models.IntegerField(default=0, verbose_name='Потери')),
                ('fouls', models.IntegerField(default=0, verbose_name='Фолы')),
                ('minutes_played', models.IntegerField(default=0, verbose_name='Минуты на площадке')),
                ('is_starter', models.BooleanField(default=False, verbose_name='В старте')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_stats', to='main.match')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_stats', to='main.player')),
            ],
            options={
                'verbose_name': 'Статистика игрока',
                'verbose_name_plural': 'Статистика игроков',
                'unique_together': {('match', 'player')},
            },
        ),
    ]
